package main

import (
    "log"
    "net/http"

    "github.com/gorilla/mux"
    
    _ "github.com/swaggo/http-swagger/example/gorilla/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

func main() {
    r := mux.NewRouter()

    // Certification Endpoint 
    s := r.PathPrefix("/certifications/api/v1").Subrouter()

    // List of paths for Certification Endpoint 
    s.HandleFunc("/cert/{Key}/{Value}", getCert).Methods("GET")
    s.HandleFunc("/certs", getCerts).Methods("GET")

    r.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), //The url pointing to API definition
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("swagger-ui"),
	)).Methods(http.MethodGet)

    log.Fatal(http.ListenAndServe(":8000", r))
}